### ISSUE TITLE
Option to Sort it by "Rating", "Newly Added", "Oldest"

### ISSUE THREAD

**Issue by FalconLoss** [anaskhan28/sieve-repo#34]
Adding a button at home which can sort the list by **Rating/Newly Added/Oldest** will be more convenient when searching for the playlist.

When I'm searching for a topic, I want to make sure that playlist I'm looking for is the most recent and highly rated.

Same can be applied for when searched a key word or clicked on genre.

Let me know if points mentioned above are not clear enough. V ;)

**Comment by anaskhan28** [comment]
Thanks for the suggestion, I'll add it and also I'm planning to add a form so that users can directly submit the video or playlist. After the user submitted the playlist it will go for verification and then after all check is passed the playlist or video will be added.

**Comment by anaskhan28** [comment]
I have added it 🫡
