### ISSUE TITLE
Add Footer to Enhance User Experience

### ISSUE THREAD

**Issue by Mefisto04** [anaskhan28/sieve-repo#44]
**Description:**
Currently, there is no footer implemented on the web app. A footer would improve the user experience by providing quick access to important information such as links to contact, privacy policy, terms of service, and social media accounts. 

**Proposed Solution:**
I would like to contribute by:
- Designing and implementing a responsive footer component.
- Including relevant links and information to improve navigation and accessibility.
- Ensuring the footer design matches the overall theme and style of the web app.
  
**Additional Information:**
- Please assign this issue to me so that I can start working on it immediately.
- Also add tag of Hacktoberfest.

**Comment by Dark-Kernel** [comment]
I'm sorry, but what are you talking about?
![image](https://github.com/user-attachments/assets/d89acc85-e258-4b57-a43f-eb4c2b5cac24)
