### ISSUE TITLE
Fix incorrect directory name in Readme

### ISSUE THREAD

**Issue by kliu57** [anaskhan28/sieve-repo#61]
**Describe the bug**
The directory name in the Installation section of the readme file should be "sieve-repo" not "sieve"

**To Reproduce**
1. Go to readme
2. Scroll down to Installation section
3. See error

**Expected behavior**
The directory name should be "sieve-repo"

**Screenshots**
![image](https://github.com/user-attachments/assets/bcd49084-73b2-4349-b01b-8969848ba1b6)

**Comment by anaskhan28** [comment]
thanks it's done
